# Generated by Django 5.2.3 on 2025-06-12 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(
                        help_text="Enter name of the asset",
                        max_length=100,
                        verbose_name="Asset Name",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Enter asset's serial number",
                        max_length=100,
                        unique=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Enter purchase date",
                        verbose_name="Purchase Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("maintenance", "Maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["asset_name"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time asset was assigned at",
                        verbose_name="Assigned At",
                    ),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="The user to whom asset is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Assignment",
                "verbose_name_plural": "Asset Assignments",
                "ordering": ["assigned_date"],
            },
        ),
    ]
